### ISSUE TITLE
Add security policies

### ISSUE THREAD

**Issue by codelitt** [codelittinc/incubator-resources#27]
- Acceptable encryption 
- Scam/Phishing safety 
- Password protection policy (Password manager, different passwords for each service, 2FA when available, etc)
- End user encryption key protection
- Network security (VPN, etc)
- App security (web and mobile)

**Comment by kaiomagalhaes** [comment]
@codelitt @halissonvit I'm taking over this one

**Comment by halissonvit** [comment]
Awesome @kaiomagalhaes . Please do

**Comment by codelitt** [comment]
That's great news.

**Comment by kaiomagalhaes** [comment]
The security document was moved to a word format
