### ISSUE TITLE
suggestions (password, crypto)

### ISSUE THREAD

**Issue by jeanmichelamblat** [codelittinc/incubator-resources#47]
Not sure where to put those:
### Strong passwords

Cracklib allows to test and ensure password policy is implemented correctly for local accounts.

$ sudo apt install libpam-cracklib
$ sudo vim /etc/pam.d/common-password

Replace the first line with:

password   requisite    pam_cracklib.so retry=3 minlen=12 difok=3 ucredit=-1 lcredit=-2 dcredit=-1 ocredit=-1
For a minimum of 12 characters, and random enough (1 uppercase, 2 lowercase, 1 digit, 1 symbol).. man pam_cracklib for all information!

So let's make password authentication a thing of the past on our server. Copy the contents of your `id_rsa.pub`[^1] on your local machine to your servers authorized keys file. Or better, use Curve 25519 ( via `ssh-keygen -t ed25519` ) instead of RSA [ECC](https://blog.cloudflare.com/a-relatively-easy-to-understand-primer-on-elliptic-curve-cryptography/), leveraging the content of your `id_ed25519.pub` file.

```
vim /home/deploy/.ssh/authorized_keys
```
#### SSH tuning: better crypto & more hardening

MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-512
ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,blowfish-cbc,aes256-ctr
KexAlgorithms curve25519-sha256@libssh.org
AllowGroups yourgroups

Cheers,

Jean-Michel

**Comment by codelitt** [comment]
@SourceFrenchy is the SSH tuning out of: https://stribika.github.io/2015/01/04/secure-secure-shell.html ?

password things look good as well, but I'll need to take a look at them.
